import type { Metadata } from 'next'
import { Montserrat, Raleway, Lato } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({
  display: 'swap',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-montserrat'
});

const lato = Lato({
  display: 'swap',
  weight: '300',
  subsets: ['latin'],
  variable: '--font-lato'
});

const raleway = Raleway({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-raleway'
});

export const metadata: Metadata = {
  title: 'Raffby Sales and Purchases Inventory',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.variable}${lato.variable}${raleway.variable}`}>
      <body>{children}</body>
    </html>
  )
}
