import type { Metadata } from 'next'
import { Montserrat, Raleway, Lato } from 'next/font/google'
import './globals.css'

const montserrat = Montserrat({
  variable: "--header-font",
  subsets: ["latin"]
});

const lato = Lato({
  variable: "--body-font",
  weight: '300',
  subsets: ["latin"]
});

const raleway = Raleway({
  variable: "--body-font2",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: 'Raffby Sales and Purchases Inventory',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${montserrat.variable}${lato.variable}${raleway.variable}`}>
      <body>{children}</body>
    </html>
  )
}
